language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -e .[dev]
test:
  - python -c "import nltk; nltk.download('punkt')"
  - pytest
deploy:
  provider: pypi
  user: ""
  password: ""
  on:
    branch: master